{
  "hash": "4414849a1b3f2901220247ef91015632",
  "result": {
    "engine": "knitr",
    "markdown": "\n---\ntitle: \"Numerical Optimisation & 1D Iterative Search\"\nsubtitle: \"ENGG7518 Research Methods for Engineers: Week 12\"\nauthor: \"Prof. Zuduo Zheng\"\ndate: \"29 July 2026\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n## Learning Objectives\nBy the end of this chapter, you should be able to:\n\n1. Explain the necessity of numerical optimisation and iterative search in complex engineering problems.\n2. Differentiate between derivative-free and derivative-based search methods.\n3. Understand the unimodality assumption and the concept of the uncertainty interval.\n4. Execute the derivative-free **Dichotomous Search Algorithm** and explain the geometric necessity of four evaluation points.\n5. Execute the **Bisection Method** using first-order derivatives and trace its convergence via iteration tables.\n:::\n\n## The Shift to Numerical Optimisation\n\nIn the previous chapters, we focused on **classical (analytical) optimisation techniques**. These methods are highly rigorous: if you can write down the explicit mathematical equations for the first and second derivatives, you can solve for the exact optimal solution algebraically by setting gradients to zero ($\\nabla f = \\mathbf{0}$). \n\nHowever, in modern engineering practice, analytical solutions are often impossible. Why?\n\n1. **Mathematical Complexity:** Objective functions are rarely neat polynomials. They frequently involve complex simulations, \"black-box\" systems, or massive datasets where explicit analytical forms of derivatives cannot be derived.\n2. **Computational Scale:** Solving massive, non-linear systems of equations algebraically is often computationally prohibitive. \n\nTo overcome this, we transition to **Numerical Optimisation (Iterative Search Procedures)**. \n\nInstead of solving for the answer in one step, a numerical algorithm starts with a rough initial guess ($x_0$) and applies mathematical rules to generate a sequence of progressively better approximations ($x_1, x_2, \\dots, x_k$). Over successive iterations, the objective function value decreases, and the sequence mathematically converges toward the optimal solution.\n\n::: {.callout-tip}\n## The Philosophy of Iterative Search\n*\"There is no need to fear any problem you are working on. If you work on it, then you are influencing the outcome. It's the problems you don't address that should concern you.\"* (James Clear)\n\nNumerical optimisation embodies this philosophy. Algorithms do not solve complex problems instantly; they take calculated, iterative steps, constantly influencing and improving the outcome until the target is successfully reached.\n:::\n\n### Classification of Numerical Methods\nWe categorise numerical search methods into two broad families:\n\n*   **Derivative-Free Methods (Direct Search):** These algorithms only evaluate the objective function $f(x)$ itself. They never calculate gradients or Hessians. They are highly robust and easy to program, though generally slower to converge. *(Example: Dichotomous Search)*.\n*   **Derivative-Based Methods:** These algorithms require the calculation of first derivatives (gradients) and sometimes second derivatives (Hessians). They converge much faster and are highly accurate, but require the objective function to be smooth and differentiable. *(Examples: Bisection Method, Steepest Descent, Newton's Method)*.\n\n## Fundamentals of 1D Search: The Uncertainty Interval\n\nBefore tackling multi-variable problems, we must master single-variable (1D) search algorithms. *(Note: 1D search methods are the backbone of advanced multi-variable algorithms, which rely on 1D \"Line Searches\" at every step!)*\n\nFor 1D optimisation, algorithms rely on continuously shrinking an **Interval of Uncertainty**, denoted as $[a, b]$. We know the optimal solution lies somewhere between $a$ and $b$, but we are uncertain of its exact location.\n\n### The Unimodality Assumption\nFor basic 1D search methods to work, we assume the objective function $f(x)$ is **unimodal** within the interval $[a, b]$. \n\n*   A **unimodal** function has exactly *one* local minimum in that interval. It smoothly drops down to the minimum and goes back up, without any secondary peaks or valleys.\n\nIf an engineering problem has multiple local minima (multi-modal), the standard practice is to perform a rough initial scan to divide the function's domain into multiple unimodal sub-intervals, applying the search algorithm independently to each.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Comparison of a unimodal function (having a single unique minimum in [a, b]) versus a multi-modal function (having multiple local minima).](week12_1d_iterative_search_files/figure-html/fig-unimodality-1.png){#fig-unimodality width=816}\n:::\n:::\n\n\n## Derivative-Free: The Dichotomous Search Method\n\nThe basic concept of Dichotomous Search is to evaluate the objective function at interior points to determine which half of the interval contains the minimum, and then discard the other half. \n\n### Why Three Points are Not Enough\nA common question arises: *Can we just evaluate the function at the two boundaries ($a$ and $b$) and the exact midpoint ($M$), giving us 3 points?*\n\n**No, three points are insufficient.** If you only evaluate $f(a)$, $f(b)$, and $f(M)$, you cannot definitively ascertain whether the true minimum lies in the left half $[a, M]$ or the right half $[M, b]$. The curve could be steeply asymmetric, hiding the true minimum in the unselected half.\n\n### The Four-Point Strategy\nTo safely reduce the uncertainty interval, we MUST evaluate **four points** by inserting *two* new interior points symmetrically around the midpoint. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Dichotomous search four-point strategy and interval reduction. Evaluating f(λ) and f(μ) around the midpoint allows discarding half of the uncertainty interval at each step.](week12_1d_iterative_search_files/figure-html/fig-dichotomous-elimination-1.png){#fig-dichotomous-elimination width=768}\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## Algorithm 1: Dichotomous Search Procedure\n**Inputs:** \n\n*   Initial interval of uncertainty: $[a, b]$\n*   Tolerance limit for stopping: $L > 0$\n*   A very small shift parameter: $\\epsilon > 0$\n\n**Initialisation:** \nSet iteration index $k = 0$. Let $a_k = a$ and $b_k = b$.\n\n**Step 1: Uncertainty Check**\nWhile the interval width $(b_k - a_k) > L$:\n\n**Step 2: Generate Interior Points**\nCalculate the two symmetric test points:\n\n*   $\\lambda_k = \\frac{a_k + b_k}{2} - \\epsilon$\n*   $\\mu_k = \\frac{a_k + b_k}{2} + \\epsilon$\n\n**Step 3: Evaluate and Update Boundaries**\nEvaluate $f(\\lambda_k)$ and $f(\\mu_k)$.\n\n*   **If $f(\\lambda_k) \\ge f(\\mu_k)$:** The curve is trending downward to the right. \n    *   Set $a_{k+1} = \\lambda_k$ and $b_{k+1} = b_k$.\n*   **If $f(\\lambda_k) < f(\\mu_k)$:** The curve is trending upward to the right. \n    *   Set $a_{k+1} = a_k$ and $b_{k+1} = \\mu_k$.\n\nIncrement $k = k + 1$ and return to Step 1.\n\n**Output:** \nOnce $(b_k - a_k) \\le L$, terminate. The approximate minimum is the midpoint: $x^* \\approx \\frac{a_k + b_k}{2}$.\n:::\n\nEach iteration effectively halves the uncertainty interval, closing in on the minimum without ever calculating a derivative.\n\n## Derivative-Based: The Bisection Method\n\nIf your objective function is continuous and differentiable ($f \\in C^1$), we can drastically improve our search efficiency using the **Bisection Method**. \n\nBecause we have access to the first derivative $f'(x)$, which reveals the exact slope of the curve, we **no longer need four points**. We only need to generate **one** additional interior point: the exact midpoint.\n\n::: {.callout-note appearance=\"simple\"}\n## Algorithm 2: Bisection Method Procedure\n**Inputs:** Initial interval $[a, b]$, stopping tolerance $L > 0$.\n**Initialisation:** Set $k = 1$, $a_k = a$, $b_k = b$.\n\n**Step 1: Midpoint Evaluation**\nWhile $(b_k - a_k) > L$:\nCalculate the midpoint: $c_k = \\frac{a_k + b_k}{2}$.\nEvaluate the derivative at the midpoint: $f'(c_k)$.\n\n**Step 2: Update Boundaries via Slope**\n\n*   **If $f'(c_k) = 0$:** The exact minimum is found! **Stop.** Output $x^* = c_k$.\n*   **If $f'(c_k) > 0$:** The slope is positive (heading upward). The minimum must lie to the left. \n    *   Set $a_{k+1} = a_k$ and $b_{k+1} = c_k$.\n*   **If $f'(c_k) < 0$:** The slope is negative (heading downward). The minimum must lie to the right.\n    *   Set $a_{k+1} = c_k$ and $b_{k+1} = b_k$.\n\nIncrement $k = k + 1$ and return to Step 1.\n:::\n\n## Worked Example: Tracing the Bisection Method\n\nLet us trace the Bisection Method on a concrete polynomial function to see exactly how the computational convergence works step-by-step.\n\n**Problem:** Find the numerical minimum point of $f(x) = 2x^6 + 3x^4 - 12x$.  \n**Given Parameters:** Initial interval $[a, b] = [0, 2]$, and a tolerance limit $L = 0.02$.\n\n**Step 1: Determine the Derivative**  \nBefore starting the iterations, we must derive the first-order derivative:\n$$ f'(x) = 12x^5 + 12x^3 - 12 $$\n\n**Step 2: Iterative Execution**\n\n*   **Iteration 1:**\n    *   **Current Interval:** $[a_1, b_1] = [0, 2]$. Interval width $\\Delta x = 2$.\n    *   **Midpoint:** $c_1 = \\frac{0 + 2}{2} = 1$.\n    *   **Evaluate slope:** Plug $c_1$ into the derivative: \n        $$ f'(1) = 12(1)^5 + 12(1)^3 - 12 = 12 $$\n\n    *   **Decision:** Since $f'(1) = 12 > 0$, the slope is positive (heading upward). Because the function is unimodal, the minimum must have already occurred to the *left*. We replace the right boundary $b$ with $c_1$.\n    *   **New Interval:** $[0, 1]$.\n\n*   **Iteration 2:**\n    *   **Current Interval:** $[a_2, b_2] = [0, 1]$. Interval width $\\Delta x = 1$.\n    *   **Midpoint:** $c_2 = \\frac{0 + 1}{2} = 0.5$.\n    *   **Evaluate slope:** \n        $$ f'(0.5) = 12(0.5)^5 + 12(0.5)^3 - 12 = -10.125 $$\n\n    *   **Decision:** Since $f'(0.5) = -10.125 < 0$, the slope is negative (heading downward). The minimum must lie further to the *right*. We replace the left boundary $a$ with $c_2$.\n    *   **New Interval:** $[0.5, 1]$.\n\n*   **Iteration 3:**\n    *   **Current Interval:** $[a_3, b_3] = [0.5, 1]$. Interval width $\\Delta x = 0.5$.\n    *   **Midpoint:** $c_3 = \\frac{0.5 + 1}{2} = 0.75$.\n    *   **Evaluate slope:** \n        $$ f'(0.75) = 12(0.75)^5 + 12(0.75)^3 - 12 \\approx -4.0898 $$\n\n    *   **Decision:** Since $f'(0.75) < 0$, the slope is still downward. The minimum lies to the *right*. We replace the left boundary again.\n    *   **New Interval:** $[0.75, 1]$.\n\n**Step 3: Summary of the Algorithm Run**\n\nIf we let a computer continue this exact logical loop, it generates the following iteration table. Notice how the interval width ($\\Delta x$) halves at each iteration, rapidly zeroing in on the true minimum.\n\n| Iteration ($k$) | Lower Bound ($a_k$) | Upper Bound ($b_k$) | Midpoint ($c_k$) | Derivative $f'(c_k)$ | Function $f(c_k)$ | Width $\\Delta x$ |\n| :---: | :---: | :---: | :---: | :---: | :---: | :---: |\n| 1 | 0.0000 | 2.0000 | **1.0000** | 12.0000 | -7.0000 | 2.0000 |\n| 2 | 0.0000 | 1.0000 | **0.5000** | -10.1250 | -5.7812 | 1.0000 |\n| 3 | 0.5000 | 1.0000 | **0.7500** | -4.0898 | -7.6948 | 0.5000 |\n| 4 | 0.7500 | 1.0000 | **0.8750** | 2.1939 | -7.8438 | 0.2500 |\n| 5 | 0.7500 | 0.8750 | **0.8125** | -1.3143 | -7.8671 | 0.1250 |\n| 6 | 0.8125 | 0.8750 | **0.8437** | 0.3396 | -7.8829 | 0.0625 |\n| 7 | 0.8125 | 0.8437 | **0.8281** | -0.5112 | -7.8815 | 0.0312 |\n| 8 | 0.8281 | 0.8437 | **0.8359** | -0.0918 | -7.8838 | **0.0156** |\n\n**Conclusion:**\nBy **Iteration 8**, the interval width $\\Delta x = 0.0156$ drops below our tolerance limit $L = 0.02$. The algorithm successfully terminates. \n\nThe derivative at the final midpoint ($f'(0.8359) \\approx -0.09$) is extremely close to zero, mathematically proving we are practically at the bottom of the curve. The highly accurate numerical approximation for the optimal solution is **$x^* \\approx 0.8359$**.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Bisection method convergence on f(x) = 2x⁶ + 3x⁴ - 12x. Vertical dashed lines show how midpoints c₁, c₂, c₃ systematically halve the search space toward x* ≈ 0.8359.](week12_1d_iterative_search_files/figure-html/fig-bisection-trajectory-1.png){#fig-bisection-trajectory width=768}\n:::\n:::\n\n",
    "supporting": [
      "week12_1d_iterative_search_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}